language: node_js
node_js:
  - "8"
script:
  - npm run build
deploy:
  provider: pages
  local-dir: build/
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master
